"""
MINIMAL MCP Server - Only exposes tools, NO business logic
Follows true MCP philosophy
"""

import json
import sys
from typing import Dict, Any
import uuid
from datetime import datetime

class MinimalMCPServer:
    """
    MCP Server that ONLY provides tools.
    All business logic is in azure_rules_engine/
    """
    
    def __init__(self):
        self.tools = {
            "list_azure_services": {
                "description": "List available Azure services for assessment",
                "parameters": {},
                "handler": self._list_services
            },
            "get_service_rules": {
                "description": "Get assessment rules for a specific Azure service",
                "parameters": {
                    "service_name": {"type": "string", "description": "Azure service name"}
                },
                "handler": self._get_service_rules
            },
            "generate_assessment": {
                "description": "Generate a complete Azure assessment",
                "parameters": {
                    "services": {"type": "array", "items": {"type": "string"}, "description": "Azure services to assess"},
                    "difficulty": {"type": "string", "enum": ["beginner", "intermediate", "advanced"], "default": "intermediate"},
                    "scenario": {"type": "string", "description": "Optional custom scenario", "default": ""}
                },
                "handler": self._generate_assessment
            }
        }
    
    def _list_services(self) -> Dict:
        """Tool 1: List available services"""
        # This just returns a static list - could load from config
        return {
            "services": [
                {"id": "virtual_machines", "name": "Virtual Machines", "category": "Compute"},
                {"id": "storage_accounts", "name": "Storage Accounts", "category": "Storage"},
                {"id": "aks", "name": "Azure Kubernetes Service", "category": "Containers"},
                {"id": "sql", "name": "Azure SQL Database", "category": "Database"},
                {"id": "key_vault", "name": "Key Vault", "category": "Security"}
            ],
            "categories": ["Compute", "Storage", "Networking", "Security", "Database", "Containers"]
        }
    
    def _get_service_rules(self, service_name: str) -> Dict:
        """Tool 2: Get rules for a service"""
        # Minimal logic - just returns rule structure
        # Actual rules loaded by the agent/rules engine
        
        service_map = {
            "virtual_machines": "Virtual Machines",
            "storage_accounts": "Storage Accounts",
            "aks": "Azure Kubernetes Service",
            "sql": "Azure SQL Database",
            "key_vault": "Key Vault"
        }
        
        display_name = service_map.get(service_name, service_name)
        
        return {
            "service": service_name,
            "display_name": display_name,
            "rule_structure": {
                "checks": "Array of validation checks",
                "weightage": "Percentage weight for each check",
                "validation_method": "SDK method to call",
                "policy_requirement": "Azure Policy requirement"
            },
            "note": "Actual rules are loaded by the rules engine, not the MCP server"
        }
    
    def _generate_assessment(self, services: list, difficulty: str = "intermediate", scenario: str = "") -> Dict:
        """Tool 3: Generate assessment - MINIMAL, just structure"""
        # This only returns the assessment STRUCTURE
        # The actual content is filled by the agent/rules engine
        
        assessment_id = str(uuid.uuid4())[:8]
        
        return {
            "assessment_id": f"assess_{assessment_id}",
            "services": services,
            "difficulty": difficulty,
            "scenario": scenario or f"Azure {difficulty} assessment",
            "structure": {
                "question": "To be generated by rules engine",
                "policy": "To be generated by rules engine", 
                "validation_script": "To be generated by rules engine"
            },
            "metadata": {
                "generated_at": datetime.utcnow().isoformat(),
                "source": "MCP Server - Structure only",
                "note": "Content will be generated by Azure Rules Engine"
            }
        }
    
    def execute_tool(self, tool_name: str, parameters: Dict = None) -> Dict:
        """Execute an MCP tool"""
        if tool_name not in self.tools:
            return {"error": f"Tool '{tool_name}' not found"}
        
        tool = self.tools[tool_name]
        
        try:
            if parameters:
                result = tool["handler"](**parameters)
            else:
                result = tool["handler"]()
            
            return {
                "tool": tool_name,
                "success": True,
                "result": result,
                "timestamp": datetime.utcnow().isoformat()
            }
        
        except Exception as e:
            return {
                "tool": tool_name,
                "success": False,
                "error": str(e),
                "timestamp": datetime.utcnow().isoformat()
            }
    
    def get_tools(self) -> Dict:
        """Get all available tools"""
        return {
            name: {
                "description": info["description"],
                "parameters": info["parameters"]
            }
            for name, info in self.tools.items()
        }

# Singleton instance
mcp_server = MinimalMCPServer()

if __name__ == "__main__":
    # Simple test
    print("MCP Server Tools:")
    for name, tool in mcp_server.get_tools().items():
        print(f"  - {name}: {tool['description']}")
    
    print("\nTesting list_azure_services:")
    result = mcp_server.execute_tool("list_azure_services")
    print(json.dumps(result, indent=2))